before_script:
  - chmod a+x ./deploy/install.sh; chmod -R a+r *

stages:
  - build
  - test
  - deploy
  
test:
  stage: test
  script: python3 manage.py test

deploy_staging:
  stage: deploy
  script: ./deploy/install.sh
  environment:
     name: staging
     url: http://photo.dsnet.ru 
  only:
    - master