# -*- coding: utf-8 -*-

"""
Django settings for HM project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kz8qy3v1lebcc3pcofjbwf4)ortx$f0&o=sc&3lnvm()om8=ej'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEPLOY = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hm_auth',
    'photogal',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'HM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'photogal.views.photogal_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'HM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# Develop Database
if not DEPLOY:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
# End Develop Database

# Deploy Database
if DEPLOY:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'hmc',
            'HOST': 'localhost',
            'USER': 'hmc',
            'PASSWORD' : '19hMc74'
        }
    }
# End Develop Database

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = False

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

#MEDIA_ROOT = r'X:/MY_DOCS/DOCUMS/Foto/'
#THUMBNAIL_BASEDIR = 'thumbs'

STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "assets"),
)

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'
PHOTOGAL_APP_NAME = 'Home Media Catalog (HMC)'
PHOTOGAL_THUMBS_DIR = 'thumbs'
PHOTOGAL_THUMBS_SIZE = 200
PHOTOGAL_THUMBS_SQUARE = True
PHOTOGAL_PREVIEW_SIZE = 1024
PHOTOGAL_THUMB_STR = 'thumb'
PHOTOGAL_PREV_STR = 'prev'
PHOTOGAL_GUEST_HASH_LENGTH = 16
if DEPLOY:
    PHOTOGAL_GUEST_URL = 'http://photo.dsnet.ru/photo/collect/guest/'
else:
    PHOTOGAL_GUEST_URL = 'http://127.0.0.1:8000/photo/collect/guest/'
